os:
  - linux

language:
  - c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsdl2-dev
      - check

script:
  - make debug
  - make debug-test
  - make release
  - make release-test
